/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'alex' at '5/21/15 2:30 PM' with Gradle 2.4
 *
 * @author alex, @date 5/21/15 2:30 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return false;
    }
}
